# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Andreas\Documents\Woschitz\RWTplus\Bauphysik\F&E\SommerlUeberw\SommerlUeberw_py\mainGUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import traceback
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import sys  # We need sys so that we can pass argv to QApplication
import os
import time
'----importierte Funktionen-------------'
from funcSUe3 import SUe3
#from funcGUIstopBtn import stopBtn
'---------------------Classes for Multithreading-------------'
class WorkerSignals(QObject):
    '''
    Defines the signals available from a running worker thread.

    Supported signals are:

    finished
        No data
    
    error
        `tuple` (exctype, value, traceback.format_exc() )
    
    result
        `object` data returned from processing, anything

    progress
        `int` indicating % progress 

    '''
    finished = pyqtSignal()
    error = pyqtSignal(tuple)
    result = pyqtSignal(object)
    progress = pyqtSignal(int)

class Worker(QRunnable):
    '''
    Worker thread

    Inherits from QRunnable to handler worker thread setup, signals and wrap-up.

    :param callback: The function callback to run on this worker thread. Supplied args and 
                     kwargs will be passed through to the runner.
    :type callback: function
    :param args: Arguments to pass to the callback function
    :param kwargs: Keywords to pass to the callback function

    '''

    def __init__(self, fn, *args, **kwargs):
        super(Worker, self).__init__()

        # Store constructor arguments (re-used for processing)
        self.fn = fn
        self.args = args
        self.kwargs = kwargs
        self.signals = WorkerSignals()    

        # Add the callback to our kwargs
        self.kwargs['progress_callback'] = self.signals.progress        
        self.stop = False

    @pyqtSlot()
    def run(self):
        '''
        Initialise the runner function with passed args, kwargs.
        '''
        
        #while self.stop != True:
            # Retrieve args/kwargs here; and fire processing using them
        try:
            result = self.fn(*self.args, **self.kwargs)
        except:
            traceback.print_exc()
            exctype, value = sys.exc_info()[:2]
            self.signals.error.emit((exctype, value, traceback.format_exc()))
        else:
            self.signals.result.emit(result)  # Return the result of the processing
        finally:
            self.signals.finished.emit()  # Done
    #def stop_it(self):
    #    self.stop = True
'---------------Classes by PYQt5--------------------'
#copy UI Changes from here
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelHKLS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelHKLS.setFont(font)
        self.labelHKLS.setObjectName("labelHKLS")
        self.gridLayout.addWidget(self.labelHKLS, 13, 0, 1, 4)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 15, 6, 1, 1)
        self.labelSimpara = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSimpara.setFont(font)
        self.labelSimpara.setObjectName("labelSimpara")
        self.gridLayout.addWidget(self.labelSimpara, 0, 0, 1, 2)
        self.labelHKLS_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelHKLS_2.setFont(font)
        self.labelHKLS_2.setObjectName("labelHKLS_2")
        self.gridLayout.addWidget(self.labelHKLS_2, 13, 4, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 14, 4, 1, 1)
        self.idealLueftenInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idealLueftenInput.setFont(font)
        self.idealLueftenInput.setObjectName("idealLueftenInput")
        self.gridLayout.addWidget(self.idealLueftenInput, 14, 1, 1, 2)
        self.textEditCalcInfo = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditCalcInfo.setMaximumSize(QtCore.QSize(16777215, 61))
        self.textEditCalcInfo.setObjectName("textEditCalcInfo")
        self.gridLayout.addWidget(self.textEditCalcInfo, 21, 0, 1, 7)
        self.CustomLueftenInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CustomLueftenInput.setFont(font)
        self.CustomLueftenInput.setObjectName("CustomLueftenInput")
        self.gridLayout.addWidget(self.CustomLueftenInput, 14, 5, 1, 1)
        self.CustomInnereLastenInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CustomInnereLastenInput.setFont(font)
        self.CustomInnereLastenInput.setObjectName("CustomInnereLastenInput")
        self.gridLayout.addWidget(self.CustomInnereLastenInput, 16, 5, 1, 1)
        self.NatLueftenInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NatLueftenInput.setFont(font)
        self.NatLueftenInput.setObjectName("NatLueftenInput")
        self.gridLayout.addWidget(self.NatLueftenInput, 18, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 15, 4, 1, 1)
        self.NachtlueftenInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NachtlueftenInput.setFont(font)
        self.NachtlueftenInput.setObjectName("NachtlueftenInput")
        self.gridLayout.addWidget(self.NachtlueftenInput, 15, 1, 1, 2)
        self.TaglueftenInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TaglueftenInput.setFont(font)
        self.TaglueftenInput.setObjectName("TaglueftenInput")
        self.gridLayout.addWidget(self.TaglueftenInput, 16, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 19, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 14, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 16, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(14, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 17, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 18, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(121, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 14, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 14, 6, 1, 1)
        self.SonnenschutzInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SonnenschutzInput.setFont(font)
        self.SonnenschutzInput.setObjectName("SonnenschutzInput")
        self.gridLayout.addWidget(self.SonnenschutzInput, 17, 1, 1, 2)
        self.startTempInput = QtWidgets.QLineEdit(self.centralwidget)
        self.startTempInput.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startTempInput.setFont(font)
        self.startTempInput.setObjectName("startTempInput")
        self.gridLayout.addWidget(self.startTempInput, 3, 1, 1, 1)
        self.MechLueftenInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MechLueftenInput.setFont(font)
        self.MechLueftenInput.setObjectName("MechLueftenInput")
        self.gridLayout.addWidget(self.MechLueftenInput, 19, 1, 1, 2)
        self.startSimulation = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startSimulation.setFont(font)
        self.startSimulation.setObjectName("startSimulation")
        self.gridLayout.addWidget(self.startSimulation, 20, 4, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 16, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 18, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 15, 0, 1, 1)
        self.CustomSonnenschutzInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CustomSonnenschutzInput.setFont(font)
        self.CustomSonnenschutzInput.setObjectName("CustomSonnenschutzInput")
        self.gridLayout.addWidget(self.CustomSonnenschutzInput, 15, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 19, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 20, 0, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 16, 3, 1, 1)
        self.labelStandort = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStandort.setFont(font)
        self.labelStandort.setObjectName("labelStandort")
        self.gridLayout.addWidget(self.labelStandort, 10, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 16, 6, 1, 1)
        self.zeitschrittInput = QtWidgets.QLineEdit(self.centralwidget)
        self.zeitschrittInput.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeitschrittInput.setFont(font)
        self.zeitschrittInput.setObjectName("zeitschrittInput")
        self.gridLayout.addWidget(self.zeitschrittInput, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 15, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 17, 3, 1, 1)
        self.stopSimulation = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopSimulation.setFont(font)
        self.stopSimulation.setObjectName("stopSimulation")
        self.gridLayout.addWidget(self.stopSimulation, 20, 6, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 2, 0, 1, 1)
        self.genauigkeitInput = QtWidgets.QLineEdit(self.centralwidget)
        self.genauigkeitInput.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.genauigkeitInput.setFont(font)
        self.genauigkeitInput.setObjectName("genauigkeitInput")
        self.gridLayout.addWidget(self.genauigkeitInput, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(14, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 11, 2, 1, 1)
        self.SeehoeheInput = QtWidgets.QLineEdit(self.centralwidget)
        self.SeehoeheInput.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SeehoeheInput.setFont(font)
        self.SeehoeheInput.setObjectName("SeehoeheInput")
        self.gridLayout.addWidget(self.SeehoeheInput, 11, 1, 1, 1)
        self.graphWidget = PlotWidget(self.centralwidget)
        self.graphWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayout.addWidget(self.graphWidget, 1, 3, 11, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
# to here

        '-------------------Multithreading------------------------'
        self.threadpool = QThreadPool()
        print("Multithreading with maximum %d threads" % self.threadpool.maxThreadCount())

        '-------------------Events--------------------------------'
        #Hier werden alle Events von Buttons verwaltet
        self.startSimulation.clicked.connect(self.Simulation)
        self.stopSimulation.clicked.connect(self.Stop)

        self.x = list(range(96))  # initializing plot x axis
        self.y = [float(self.startTempInput.text())] * 96  # initializing plot y axis

        self.graphWidget.setBackground('w')

        pen = pg.mkPen(color=(51, 51, 255))
        self.data_line =  self.graphWidget.plot(self.x, self.y, pen=pen)
        self.graphWidget.getPlotItem().hideAxis('bottom')
        self.timer = QtCore.QTimer()
        self.timer.setInterval(200)
        self.timer.timeout.connect(self.update_plot_data)
        self.timer.start()
        self.line = 0
        self.progress = 0
        self.progressLimit = 100

    def update_plot_data(self):
        abbruchTxt = open('Abbruch.txt', 'r')
        if abbruchTxt.read() == 'False' and self.progress < self.progressLimit: #Umrechnung des Simulationsfortschrittes in Prozent
            indexTxt = open('index.txt', 'r')
            indexTxtLines = indexTxt.readlines()
            for i in range(len(indexTxtLines)):
                indexTxtLines[i] = indexTxtLines[i].replace('\n', '')
            self.progress = float(indexTxtLines[len(indexTxtLines) - 1]) * float(self.zeitschrittInput.text()) / 86400 * 100
            self.progressBar.setProperty("value", self.progress)
            self.textEditCalcInfo.setText(open('time.txt', 'r').read())
            
                
        else:
            self.progressBar.setProperty("value", 0)
            self.progress = 0

        #Dynamic graph plot update for Qtimer
        filename = 'graphTop.txt'
        if os.stat(filename).st_size != 0:
            if self.line == 0:
                time.sleep(0.2)

            file = open(filename)
            fileLines = file.readlines()
            for i in range(len(fileLines)):
                fileLines[i] = fileLines[i].replace('\n', '')
            self.x = self.x[1:]  # Remove the first y element.
            self.x.append(self.x[-1] + 1)  # Add a new value 1 higher than the last.
            self.y = self.y[1:]  # Remove the first 
            self.y.append(float(fileLines[self.line]))  # Add a new value.
            self.data_line.setData(self.x, self.y)  # Update the data.
            file.close()
            self.line += 1
            #self.counter += 1
            if self.line == len(fileLines):
                self.line = 0

        else:
            print('No Data')
            self.x = self.x[1:]  # Remove the first x element. 
            self.x.append(self.x[-1] + 1)  # Add a new value 1 higher than the last.
            self.y = self.y[1:]  # Remove the first 
            self.y.append(float(self.startTempInput.text()))  # Add a new value.
            self.data_line.setData(self.x, self.y)


#here the functions for the workers are defined
    def SUe3_fn_worker(self, progress_callback):
        open('graphTop.txt', 'w').close()
        SUe3(float(self.zeitschrittInput.text()), float(self.genauigkeitInput.text()), float(self.startTempInput.text()), bool(int(self.idealLueftenInput.text())), bool(int(self.NachtlueftenInput.text())), 
            bool(int(self.TaglueftenInput.text())), bool(int(self.SonnenschutzInput.text())), bool(int(self.NatLueftenInput.text())), bool(int(self.MechLueftenInput.text())), 
            float(self.SeehoeheInput.text()), bool(int(self.CustomLueftenInput.text())), bool(int(self.CustomSonnenschutzInput.text())), bool(int(self.CustomInnereLastenInput.text())))


        '------------------Functions by PyQt5--------------------'
#copy after changes in .ui by Designer from here 
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SUe-Thermischer Komfort"))
        self.labelHKLS.setText(_translate("MainWindow", "HKLS-Steuerung (automatisch)"))
        self.label_19.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.labelSimpara.setText(_translate("MainWindow", "Simulationsparameter"))
        self.labelHKLS_2.setText(_translate("MainWindow", "HKLS-Steuerung (aus Input Datei)"))
        self.label_17.setText(_translate("MainWindow", "Lüften"))
        self.idealLueftenInput.setText(_translate("MainWindow", "1"))
        self.textEditCalcInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CustomLueftenInput.setText(_translate("MainWindow", "0"))
        self.CustomInnereLastenInput.setText(_translate("MainWindow", "1"))
        self.NatLueftenInput.setText(_translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", "Sonnenschutz"))
        self.NachtlueftenInput.setText(_translate("MainWindow", "0"))
        self.TaglueftenInput.setText(_translate("MainWindow", "1"))
        self.label_14.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.label_4.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.label_23.setText(_translate("MainWindow", "Innere Lasten"))
        self.label_2.setText(_translate("MainWindow", "s"))
        self.label_8.setText(_translate("MainWindow", "Sonnenschutz"))
        self.label_12.setText(_translate("MainWindow", "Nat. Lüftung"))
        self.label.setText(_translate("MainWindow", "Zeitschritt"))
        self.label_3.setText(_translate("MainWindow", "ideal Lüften"))
        self.label_18.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.SonnenschutzInput.setText(_translate("MainWindow", "0"))
        self.startTempInput.setText(_translate("MainWindow", "30"))
        self.MechLueftenInput.setText(_translate("MainWindow", "0"))
        self.startSimulation.setText(_translate("MainWindow", "Start"))
        self.label_16.setText(_translate("MainWindow", "Taglüften"))
        self.label_11.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.label_6.setText(_translate("MainWindow", "Nachtlüften"))
        self.CustomSonnenschutzInput.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Mech. Lüftung"))
        self.label_10.setText(_translate("MainWindow", "Seehöhe"))
        self.label_15.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.labelStandort.setText(_translate("MainWindow", "Standort"))
        self.label_24.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.zeitschrittInput.setText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.label_7.setText(_translate("MainWindow", "1 = Ja //  0 = Nein"))
        self.stopSimulation.setText(_translate("MainWindow", "Stop"))
        self.label_22.setText(_translate("MainWindow", "Genauigkeit"))
        self.genauigkeitInput.setText(_translate("MainWindow", "1e-3"))
        self.label_26.setText(_translate("MainWindow", "Starttemperatur"))
        self.label_25.setText(_translate("MainWindow", "°C"))
        self.label_9.setText(_translate("MainWindow", "m"))
        
#to here

    '----------------------Funktionen----------------------------' 
    #Hier finden sich alle selbst geschriebenen Funktionen zu den Events

    
    def Simulation(self):        
        file = open('Abbruch.txt', 'w')
        file.write('False')
        self.line = 0
        open('graphTop.txt', 'w').close()
        open('time.txt', 'w').close()
        
        

        #SUe3(float(self.zeitschrittInput.text()), float(self.genauigkeitInput.text()), float(self.startTempInput.text()), bool(int(self.idealLueftenInput.text())), bool(int(self.NachtlueftenInput.text())), 
        #    bool(int(self.TaglueftenInput.text())), bool(int(self.SonnenschutzInput.text())), bool(int(self.NatLueftenInput.text())), bool(int(self.MechLueftenInput.text())), 
        #    float(self.SeehoeheInput.text()), bool(int(self.CustomLueftenInput.text())), bool(int(self.CustomSonnenschutzInput.text())), bool(int(self.CustomInnereLastenInput.text())))

        worker1 = Worker(self.SUe3_fn_worker) # any other args, kwargs are passed to the run function
        # execute
        self.threadpool.start(worker1)

        

   
    def Stop(self):
        file = open('Abbruch.txt', 'w')
        file.write('True')
        self.line = 0
        open('graphTop.txt', 'w').close()
        open('time.txt', 'w').close()
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
